version: '3'

services:
  workspace:
    builds:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      hello:
      args:
        user: ${DEVCONTAINER_USER}
        userUID: ${DEVCONTAINER_USER_UID}
        userGID: ${DEVCONTAINER_USER_GID}
    command: /bin/sh -c 'while sleep 1000; do :; done'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ..:/mykspace:${DEVCONTAINER_VOLUME_CONSISTENCY}
      - ~/.gitconfig:/home/${DEVCONTAINER_USER}/.gitconfig:ro
      - ~/.gitignore:/home/${DEVCONTAINER_USER}/.gitignore:ro
      - ~/.ssh:/home/${DEVCONTAINER_USER}/.ssh:ro
      - workspace-data:/data:${DEVCONTAINER_VOLUME_CONSISTENCY}
      - workspace-vscode:/home/${DEVCONTAINER_USER}/.vscode-server

volumes:
  workspace-data:
  workspace-vscode:
